"""agrega columnas usuario nombre telefono role is_active invitation

Revision ID: 08b66222bf3a
Revises: ecea98fb65a4
Create Date: 2026-03-30 17:47:34.318157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08b66222bf3a'
down_revision = 'ecea98fb65a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negocio', schema=None) as batch_op:
        batch_op.drop_column('reset_token')
        batch_op.drop_column('reset_token_expira')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negocio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token_expira', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('reset_token', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
