"""inicial

Revision ID: 1c459d27896e
Revises: 
Create Date: 2026-03-30 17:34:54.628605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c459d27896e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negocio', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expira')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negocio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expira', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
