"""descripcion del cambio

Revision ID: ff02561c8823
Revises: 1c459d27896e
Create Date: 2026-03-30 17:35:55.930873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff02561c8823'
down_revision = '1c459d27896e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negocio', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expira')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negocio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expira', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
